# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/comms/algocomm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/comms/algocomm.proto',
  package='algo',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18src/comms/algocomm.proto\x12\x04\x61lgo\"\x07\n\x05\x45mpty\"\x1e\n\rStartResponse\x12\r\n\x05start\x18\x01 \x01(\x08\"\x1e\n\x0cStatusString\x12\x0e\n\x06status\x18\x01 \x01(\t\"#\n\x0eObstacleString\x12\x11\n\tobstacles\x18\x01 \x01(\t\"\x15\n\x07ImageID\x12\n\n\x02id\x18\x01 \x01(\t\")\n\rRobotPosition\x12\x18\n\x10robotCoordinates\x18\x01 \x01(\t\"7\n\x0bMoveRequest\x12\x16\n\x0eradius_indexed\x18\x01 \x01(\x05\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\"%\n\x0cMoveResponse\x12\x15\n\rtime_required\x18\x01 \x01(\x01\"\x1e\n\rRadiiResponse\x12\r\n\x05radii\x18\x01 \x03(\x01\x32\xe3\x02\n\x04\x61lgo\x12\x39\n\x12ReceiveCoordinates\x12\x0b.algo.Empty\x1a\x14.algo.ObstacleString\"\x00\x12-\n\x04Move\x12\x11.algo.MoveRequest\x1a\x12.algo.MoveResponse\x12,\n\x08GetRadii\x12\x0b.algo.Empty\x1a\x13.algo.RadiiResponse\x12\x31\n\x0bMoveVirtual\x12\x13.algo.RobotPosition\x1a\x0b.algo.Empty\"\x00\x12+\n\x0bTakePicture\x12\r.algo.ImageID\x1a\x0b.algo.Empty\"\x00\x12\x31\n\x0cUpdateStatus\x12\x12.algo.StatusString\x1a\x0b.algo.Empty\"\x00\x12\x30\n\nCheckStart\x12\x0b.algo.Empty\x1a\x13.algo.StartResponse\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='algo.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=41,
)


_STARTRESPONSE = _descriptor.Descriptor(
  name='StartResponse',
  full_name='algo.StartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='algo.StartResponse.start', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=73,
)


_STATUSSTRING = _descriptor.Descriptor(
  name='StatusString',
  full_name='algo.StatusString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='algo.StatusString.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=105,
)


_OBSTACLESTRING = _descriptor.Descriptor(
  name='ObstacleString',
  full_name='algo.ObstacleString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='obstacles', full_name='algo.ObstacleString.obstacles', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=142,
)


_IMAGEID = _descriptor.Descriptor(
  name='ImageID',
  full_name='algo.ImageID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='algo.ImageID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=165,
)


_ROBOTPOSITION = _descriptor.Descriptor(
  name='RobotPosition',
  full_name='algo.RobotPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='robotCoordinates', full_name='algo.RobotPosition.robotCoordinates', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=208,
)


_MOVEREQUEST = _descriptor.Descriptor(
  name='MoveRequest',
  full_name='algo.MoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='radius_indexed', full_name='algo.MoveRequest.radius_indexed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='algo.MoveRequest.distance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=265,
)


_MOVERESPONSE = _descriptor.Descriptor(
  name='MoveResponse',
  full_name='algo.MoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_required', full_name='algo.MoveResponse.time_required', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=304,
)


_RADIIRESPONSE = _descriptor.Descriptor(
  name='RadiiResponse',
  full_name='algo.RadiiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='radii', full_name='algo.RadiiResponse.radii', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=336,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['StartResponse'] = _STARTRESPONSE
DESCRIPTOR.message_types_by_name['StatusString'] = _STATUSSTRING
DESCRIPTOR.message_types_by_name['ObstacleString'] = _OBSTACLESTRING
DESCRIPTOR.message_types_by_name['ImageID'] = _IMAGEID
DESCRIPTOR.message_types_by_name['RobotPosition'] = _ROBOTPOSITION
DESCRIPTOR.message_types_by_name['MoveRequest'] = _MOVEREQUEST
DESCRIPTOR.message_types_by_name['MoveResponse'] = _MOVERESPONSE
DESCRIPTOR.message_types_by_name['RadiiResponse'] = _RADIIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.Empty)
  })
_sym_db.RegisterMessage(Empty)

StartResponse = _reflection.GeneratedProtocolMessageType('StartResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTRESPONSE,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.StartResponse)
  })
_sym_db.RegisterMessage(StartResponse)

StatusString = _reflection.GeneratedProtocolMessageType('StatusString', (_message.Message,), {
  'DESCRIPTOR' : _STATUSSTRING,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.StatusString)
  })
_sym_db.RegisterMessage(StatusString)

ObstacleString = _reflection.GeneratedProtocolMessageType('ObstacleString', (_message.Message,), {
  'DESCRIPTOR' : _OBSTACLESTRING,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.ObstacleString)
  })
_sym_db.RegisterMessage(ObstacleString)

ImageID = _reflection.GeneratedProtocolMessageType('ImageID', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEID,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.ImageID)
  })
_sym_db.RegisterMessage(ImageID)

RobotPosition = _reflection.GeneratedProtocolMessageType('RobotPosition', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTPOSITION,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.RobotPosition)
  })
_sym_db.RegisterMessage(RobotPosition)

MoveRequest = _reflection.GeneratedProtocolMessageType('MoveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVEREQUEST,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.MoveRequest)
  })
_sym_db.RegisterMessage(MoveRequest)

MoveResponse = _reflection.GeneratedProtocolMessageType('MoveResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVERESPONSE,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.MoveResponse)
  })
_sym_db.RegisterMessage(MoveResponse)

RadiiResponse = _reflection.GeneratedProtocolMessageType('RadiiResponse', (_message.Message,), {
  'DESCRIPTOR' : _RADIIRESPONSE,
  '__module__' : 'src.comms.algocomm_pb2'
  # @@protoc_insertion_point(class_scope:algo.RadiiResponse)
  })
_sym_db.RegisterMessage(RadiiResponse)



_ALGO = _descriptor.ServiceDescriptor(
  name='algo',
  full_name='algo.algo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=339,
  serialized_end=694,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReceiveCoordinates',
    full_name='algo.algo.ReceiveCoordinates',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_OBSTACLESTRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Move',
    full_name='algo.algo.Move',
    index=1,
    containing_service=None,
    input_type=_MOVEREQUEST,
    output_type=_MOVERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRadii',
    full_name='algo.algo.GetRadii',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RADIIRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MoveVirtual',
    full_name='algo.algo.MoveVirtual',
    index=3,
    containing_service=None,
    input_type=_ROBOTPOSITION,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TakePicture',
    full_name='algo.algo.TakePicture',
    index=4,
    containing_service=None,
    input_type=_IMAGEID,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStatus',
    full_name='algo.algo.UpdateStatus',
    index=5,
    containing_service=None,
    input_type=_STATUSSTRING,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckStart',
    full_name='algo.algo.CheckStart',
    index=6,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALGO)

DESCRIPTOR.services_by_name['algo'] = _ALGO

# @@protoc_insertion_point(module_scope)
