# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image/imagecomm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image/imagecomm.proto',
  package='imagecomm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15image/imagecomm.proto\x12\timagecomm\"\x07\n\x05\x45mpty\"\x19\n\x08PicArray\x12\r\n\x05image\x18\x01 \x03(\x05\"\x1f\n\rProcessResult\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32L\n\tImageComm\x12?\n\x0cProcessImage\x12\x13.imagecomm.PicArray\x1a\x18.imagecomm.ProcessResult\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='imagecomm.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=43,
)


_PICARRAY = _descriptor.Descriptor(
  name='PicArray',
  full_name='imagecomm.PicArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='imagecomm.PicArray.image', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=70,
)


_PROCESSRESULT = _descriptor.Descriptor(
  name='ProcessResult',
  full_name='imagecomm.ProcessResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='imagecomm.ProcessResult.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['PicArray'] = _PICARRAY
DESCRIPTOR.message_types_by_name['ProcessResult'] = _PROCESSRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'image.imagecomm_pb2'
  # @@protoc_insertion_point(class_scope:imagecomm.Empty)
  })
_sym_db.RegisterMessage(Empty)

PicArray = _reflection.GeneratedProtocolMessageType('PicArray', (_message.Message,), {
  'DESCRIPTOR' : _PICARRAY,
  '__module__' : 'image.imagecomm_pb2'
  # @@protoc_insertion_point(class_scope:imagecomm.PicArray)
  })
_sym_db.RegisterMessage(PicArray)

ProcessResult = _reflection.GeneratedProtocolMessageType('ProcessResult', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSRESULT,
  '__module__' : 'image.imagecomm_pb2'
  # @@protoc_insertion_point(class_scope:imagecomm.ProcessResult)
  })
_sym_db.RegisterMessage(ProcessResult)



_IMAGECOMM = _descriptor.ServiceDescriptor(
  name='ImageComm',
  full_name='imagecomm.ImageComm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=105,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessImage',
    full_name='imagecomm.ImageComm.ProcessImage',
    index=0,
    containing_service=None,
    input_type=_PICARRAY,
    output_type=_PROCESSRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGECOMM)

DESCRIPTOR.services_by_name['ImageComm'] = _IMAGECOMM

# @@protoc_insertion_point(module_scope)
