# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from image import imagecomm_pb2 as image_dot_imagecomm__pb2


class ImageCommStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessImage = channel.unary_unary(
                '/imagecomm.ImageComm/ProcessImage',
                request_serializer=image_dot_imagecomm__pb2.PicArray.SerializeToString,
                response_deserializer=image_dot_imagecomm__pb2.ProcessResult.FromString,
                )


class ImageCommServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageCommServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessImage,
                    request_deserializer=image_dot_imagecomm__pb2.PicArray.FromString,
                    response_serializer=image_dot_imagecomm__pb2.ProcessResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imagecomm.ImageComm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageComm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imagecomm.ImageComm/ProcessImage',
            image_dot_imagecomm__pb2.PicArray.SerializeToString,
            image_dot_imagecomm__pb2.ProcessResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
